### ISSUE TITLE
Update gem version and republish

### ISSUE THREAD

**Issue by shayhowe** [edgecase/middleman-gh-pages#12]
Currently the gem on RubyGems.org is not up-to-date with the GitHub repository. A merge from 9 months ago, fixing the "[fatal: You are on a branch yet to be born](https://github.com/neo/middleman-gh-pages/pull/1)" error, does not look to be present in the gem.

Changing the Gemfile gem source from RubyGems.org to GitHub, `gem "middleman-gh-pages", :git => "git@github.com:neo/middleman-gh-pages.git"`, resolves this issue. It would seem the gem needs to be republished.

**Comment by rmm5t** [comment]
Closing this out. I'm currently working on merging PRs and closing issues. Afterwards and some manual testing, I'm going to bump the version and publish a new release.
