### ISSUE TITLE
Error when publishing

### ISSUE THREAD

**Issue by frechg** [edgecase/middleman-gh-pages#20]
Working from the master branch I commit my changes and push to master.

I then run the ``` rake build ``` command which finishes successfully.

I then run ```rake publish``` and get the following error:

```
...
git push origin gh-pages
error: src refspec gh-pages does not match any.
error: failed to push some refs to 'git@github.com:frechg/portfolio_2014.git'
rake aborted!
Command failed with status (1): [git push origin gh-pages...]
/Users/galenfrechette/.rvm/gems/ruby-2.1.0/gems/middleman-gh-pages-0.0.3/lib/middleman-gh-pages/tasks/gh-pages.rake:81:in `block (2 levels) in <top (required)>'
/Users/galenfrechette/.rvm/gems/ruby-2.1.0/gems/middleman-gh-pages-0.0.3/lib/middleman-gh-pages/tasks/gh-pages.rake:74:in `block in <top (required)>'
Tasks: TOP => publish
(See full trace by running task with --trace)
```

**Comment by flavorjones** [comment]
Workaround: delete the `build` subdirectory, and then `rake publish`.

The problem here is that if you run `rake build` (to test your site), then the "build" subdirectory won't be correctly set up as a clone of the `gh-pages` branch.

**Comment by wkoszek** [comment]
+1. Just upgraded my system and I'm hitting the same issue.

@flavorjones Tried that, since this is mostly how I was solving problems with deployment. But this time it didn't work. I think something got messed up during deployment.

**Comment by simonc** [comment]
For information it comes from `middleman-build` removing the `.git` folder, or at least re-initializing it. I don't have a workaround yet though :disappointed:

**Comment by bjankord** [comment]
Ran into this issue as well. Ended up writing a custom rake task but would be curious if anyone gets this working again.

@simonc Are you referring to the `.git` folder in the `build` directory or the root directory? Might be able to store it off temporarily then move it back so `middleman-build` doesn't futz with it.

**Comment by simonc** [comment]
@bjankord The .git in the build directory. I ended up moving to middleman-deploy that supports gh-pages :)

**Comment by bjankord** [comment]
@simonc Ah ok. I started looking at middleman-gh-pages because I ran into a [github pages deploy issue with middleman-deploy](https://github.com/middleman-contrib/middleman-deploy/issues/114). I got the idea of moving the `.git` directory out of the `build` directory and running `middleman build` and then moving it back from @rpbaptist's [comment over here](https://github.com/middleman-contrib/middleman-deploy/issues/112#issuecomment-166840947). Curious if you ever got your site to deploy to github pages.

**Comment by rmm5t** [comment]
I just submitted a pull-request (#32) that fixes this issue. I used to have collaborator access before this project moved from @neo to @edgecase, but no longer :cry:. 

/cc @adamlogic I'm glad to get this merged and also look at other currently open issues and pull-requests if it helps. I can also coordinate new rubygems releases if you want to add me there too (same email address as listed on my github profile).

**Comment by adamlogic** [comment]
Thanks Ryan! I also no longer have collaborator access. @mdoel can you add @rmm5t as a collaborator to this repo? I think he's the only one maintaining it anymore.

**Comment by rmm5t** [comment]
@adamlogic Thanks. It does look like you're currently the only one with rubygems publish access though.  Just FYI. Might want to open that up a bit too. https://rubygems.org/gems/middleman-gh-pages

**Comment by adamlogic** [comment]
> Might want to open that up a bit too.

Done.

**Comment by mdoel** [comment]
@rmm5t you should have commit access now

**Comment by rmm5t** [comment]
@mdoel Thanks. I got the invite and accepted it, but it doesn't look like the team I was assigned write access to has access to any repositories yet. 

![teams edgecase 2016-02-16 13-03-41](https://cloud.githubusercontent.com/assets/740/13089453/d78a22e4-d4ad-11e5-8a64-9631d8742f0d.png)

**Comment by mdoel** [comment]
d'oh try again @rmm5t - my bad
