### ISSUE TITLE
Ability to configure branches

### ISSUE THREAD

**Issue by mehulkar** [edgecase/middleman-gh-pages#26]
I'm looking to use `middleman` for a user page (vs a project page), and that requires that the build is in the `master` branch. So I'd like to keep my source in some other branch and then be able to `rake publish` to the `master` branch.

**Comment by turnbullm** [comment]
+1

**Comment by josephholsten** [comment]
how does the implementation #28 strike you?

**Comment by mehulkar** [comment]
@josephholsten works great. Maybe add a usage note in the README as part of that PR?

**Comment by josephholsten** [comment]
good point

**Comment by josephholsten** [comment]
@mehulkar how's that look?

**Comment by mehulkar** [comment]
Code looks fine! Thanks for asking. (Not an active user anymore though, so
I haven't tested it).

On Monday, May 4, 2015, Joseph Anthony Pasquale Holsten <
notifications@github.com> wrote:

> @mehulkar <https://github.com/mehulkar> how's that look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/neo/middleman-gh-pages/issues/26#issuecomment-98822118>
> .
>


-- 

------
Mehul Kar
@mehulkar

**Comment by rmm5t** [comment]
Closed by #28

**Comment by kahboom** [comment]
This doesn't seem to be working for me?

<img width="562" alt="screen shot 2017-03-22 at 7 55 17 pm" src="https://cloud.githubusercontent.com/assets/3844502/24226231/a275e9f2-0f3b-11e7-9489-3b7b94bd6968.png">

[These](https://gist.github.com/kahboom/47a118eed907950cbaa7d463b2f35741) are my configuration settings (i.e. I also tried by setting an ENV var in my `Rakefile`). Surely it's a stupid mistake on my part that I'm just not noticing.
