### ISSUE TITLE
`Couldn't find remote ref gh-pages` on 0.3.0

### ISSUE THREAD

**Issue by coreyward** [edgecase/middleman-gh-pages#33]
I'm getting the following error on 0.3.0 when trying to publish to a new repo:

```bash
$ rake publish
mkdir -p ~/website/build
cd ~/website
cd -
cd ~/website/build
git init
Initialized empty Git repository in ~/website/build/.git/
git remote add origin git@github.com:coreyward/website.git
git fetch --depth 1 origin gh-pages
fatal: Couldn't find remote ref gh-pages
rake aborted!
Command failed with status (128): [git fetch --depth 1 origin gh-pages...]
~/.rvm/gems/ruby-2.3.0/gems/middleman-gh-pages-0.3.0/lib/middleman-gh-pages/tasks/gh-pages.rake:42:in `block (2 levels) in <top (required)>'
```

The issue appears to have been introduced by the changes to `git fetch` in 37908b0f9e1f5468bf20a452f9807cbfb14c9195. Specifying 68702c224378911dba6c291a8e374cf7c926ec2d in my Gemfile and deleting the `build` directory results in the `gh-pages` branch being created on the remote successfully.

**Comment by rmm5t** [comment]
Thanks for the report. I'm a bit swamped at the moment, but I'll dig in as soon as I can.

**Comment by rmm5t** [comment]
Try v0.3.1. You will probably have to first `rm -rf build` your build directory first, and then re-run `bundle exec rake publish`.

Sorry about the bug there. That was a kind of major issue for those who hadn't yet made a gh-pages branch. Thanks for pointing it out.
